version: '3.8'

services:
  web:
    build:
      args:
        APP_DIR: 'app'
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm rebuild node-sass && npm run dev"
    ports:
      - 3000:3000
      - 8080:8080
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules